stages:
  - build
  - deploy

variables:
  IMAGE_NAME: ghcr.io/Damsmh/fakeobsidian
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest -f FakeObsidian/Dockerfile .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - master

deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
  script:
    - docker compose pull
    - docker compose up -d
  only:
    - master