services:
  fakeobsidian.api:
    image: ghcr.io/damsmh/fakeobsidian:latest
    build:
      context: .
      dockerfile: FakeObsidian/Dockerfile
    container_name: fakeobsidian-api
    restart: unless-stopped
    ports:
      - "${API_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__PostgreSQL=Host=fakeobsidian.postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Pooling=true;MinPoolSize=10;MaxPoolSize=150;Keepalive=60
      - ConnectionStrings__Redis=fakeobsidian.redis:6379
    depends_on:
      fakeobsidian.postgres:
        condition: service_healthy
      fakeobsidian.redis:
        condition: service_healthy

  fakeobsidian.postgres:
    image: postgres:17-alpine
    container_name: fakeobsidian-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  fakeobsidian.redis:
    image: redis:7-alpine
    container_name: fakeobsidian-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
